### ISSUE TITLE
jekyll-docs error message after installing gem

### ISSUE THREAD

**Issue by 2manyprojects2littletime** [jekyll/jekyll-docs#5] opened 2016-02-03 17:25 UTC
When I run the `jekyll docs` cmd after installing the gem I still get an error message.  Is there an integration step I'm missing?

<pre><code>$ jekyll docs
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.
$ gem install jekyll-docs`
[...]
$ gem list --local

*** LOCAL GEMS ***

[...]
jekyll (3.1.1, 3.1.0)
jekyll-docs (3.1.1)
jekyll-import (0.10.0)
jekyll-sass-converter (1.4.0)
jekyll-watch (1.3.1)
[...]

$ jekyll docs
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.</code></pre>

**Comment by parkr** [comment] 2016-02-03 19:47
@2manyprojects2littletime Try running `jekyll docs --verbose --trace`.

**Comment by 2manyprojects2littletime** [comment] 2016-02-04 00:39
No love.
<pre><code>$ jekyll docs --verbose --trace
jekyll 3.1.1 | Error:  Whoops, we can't understand your command.
jekyll 3.1.1 | Error:  invalid option: --verbose
jekyll 3.1.1 | Error:  Run your command again with the --help switch to see available options.

$ jekyll docs --trace
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.

$ jekyll docs --verbose --trace --help
jekyll 3.1.1 | Error:  Whoops, we can't understand your command.
jekyll 3.1.1 | Error:  invalid option: --verbose
jekyll 3.1.1 | Error:  Run your command again with the --help switch to see available options.

$ jekyll docs --verbose --help
jekyll 3.1.1 | Error:  Whoops, we can't understand your command.
jekyll 3.1.1 | Error:  invalid option: --verbose
jekyll 3.1.1 | Error:  Run your command again with the --help switch to see available options.
</code></pre>

**Comment by parkr** [comment] 2016-02-04 02:59
@2manyprojects2littletime Did you try using a `Gemfile`? That's pretty strange – it does a `require "jekyll-docs"` and creates the stubbed "You must install" command only if it fails to `require`. Can you do this?

```console
$ irb
>> require 'jekyll-docs'
```

**Comment by 2manyprojects2littletime** [comment] 2016-02-04 14:39
I'm not a rubyist day-to-day, but I had a friend walk me through the gemfile procedure, here's what I tried:
Gemfile:
<pre><code>source 'https://rubygems.org'
gem 'jekyll-docs'
</code></pre>
<pre><code>$ bundle install
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using colorator 0.1
Using ffi 1.9.10
Using sass 3.4.21
Using rb-fsevent 0.9.7
Using kramdown 1.9.0
Using liquid 3.0.6
Using mercenary 0.3.5
Using rouge 1.10.1
Using safe_yaml 1.0.4
Using bundler 1.11.2
Using rb-inotify 0.9.5
Using jekyll-sass-converter 1.4.0
Using listen 3.0.5
Using jekyll-watch 1.3.1
Using jekyll 3.1.1
Using jekyll-docs 3.1.1
Bundle complete! 1 Gemfile dependency, 16 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ jekyll docs
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.</code></pre>

No love in imode either:
<pre><code>$ irb
irb(main):001:0> require 'jekyll-docs'
LoadError: cannot load such file -- jekyll-docs
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /usr/local/bin/irb:11:in `<main>'</pre></code>

**Comment by parkr** [comment] 2016-02-05 01:47
Gemfile:

```ruby
gem "jekyll-docs",  group: [:jekyll_plugins]
```

Then run: `bundle exec jekyll docs`. Now does it work?

**Comment by saush** [comment] 2016-02-15 07:41
After installation I just had the same error. Went to the `jekyll-docs` gem directory and ran...

`jekyll serve`

That command exited with...

`Configuration file: C:/ruby217/lib/ruby/gems/2.1.0/gems/jekyll-docs-3.1.1/site/_config.yml
    Dependency Error: Yikes! It looks like you don't have jekyll-feed or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-feed' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.1.1 | Error:  jekyll-feed`

So I did...

`gem install jekyll-feed`
`jekyll serve`

This time...

`Configuration file: C:/ruby217/lib/ruby/gems/2.1.0/gems/jekyll-docs-3.1.1/site/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-redirect-from or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-redirect-from' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.1.1 | Error:  jekyll-redirect-from`

Again...

`gem install jekyll-redirect-from`
`jekyll serve`

This time...

`Configuration file: C:/ruby217/lib/ruby/gems/2.1.0/gems/jekyll-docs-3.1.1/site/_config.yml
            Source: C:/ruby217/lib/ruby/gems/2.1.0/gems/jekyll-docs-3.1.1/site
       Destination: C:/ruby217/lib/ruby/gems/2.1.0/gems/jekyll-docs-3.1.1/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Dependency Error: Yikes! It looks like you don't have pygments or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- pygments' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
  Liquid Exception: pygments in C:/ruby217/lib/ruby/gems/2.1.0/gems/jekyll-docs-3.1.1/site/_docs/assets.md
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    pygments`

So I opened `_config.yml` (and there at the end of file were those 2 gems listed which I installed above. I should have opened the `_config.yml` first) and changed this line...

`highlighter: pygments`

to..

`highlighter: rouge`

because `rouge` was already installed on system. After that I ran...

`jekyll serve`

and voila. It worked.

Conclusion: required dependencies are not resolving correctly.

**Comment by tomireland** [comment] 2016-02-15 21:08
I'm also receiving the error _"You must install the 'jekyll-docs' gem to use the 'jekyll docs' command."_ when running `jekyll-docs`.

If I run `jekyll docs --verbose --trace`, I get the following output:

```
jekyll 3.1.1 | Error:  Whoops, we can't understand your command.
jekyll 3.1.1 | Error:  invalid option: --verbose
jekyll 3.1.1 | Error:  Run your command again with the --help switch to see available options.
```
Any pointers on what the issue could be and if you need any further information?

Cheers!

**Comment by julianorafael** [comment] 2016-02-16 00:09
I'm having the same problem here. If I run `jekyll docs -h`, I get:
`jekyll docs

Usage:

  jekyll docs

Options:
        -h, --help         Show this message
        -v, --version      Print the name and version
        -t, --trace        Show the full backtrace when an error occurs
`
But if I run `jekyll docs`:
`You must install the 'jekyll-docs' gem to use the 'jekyll docs' command. `

The version options return `docs`.

**Comment by 2manyprojects2littletime** [comment] 2016-02-16 00:36
No love with the alternate Gemfile
<pre><code>$ cat Gemfile
gem "jekyll-docs", group: [:jekyll_plugins]
$ bundle exec jekyll docs
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.
</code></pre>

**Comment by parkr** [comment] 2016-02-16 04:25
Hmmmm this may be a slightly larger issue. It seems we're not shipping a command which is, of course, not going to go so well for us! Let me take a closer look this week.

**Comment by ciacon** [comment] 2016-02-17 05:08
I can confirm - same issue here

**Comment by jemagee** [comment] 2016-02-18 20:29
Not to pile on but to be more specific I'm running ruby 2.2.2, on a mac running os 10.10.5 (i already rebuilt one computer after installing el capitan i don't wanna do it again) and get the same error.  I thought it was me

**Comment by parkr** [comment] 2016-02-20 01:25
Fixed! You can now run `jekyll docs` for Jekyll v3.0.3. Due to restrictions on gem republishing, v3.1.1 won't be available; we'll publish v3.1.2 soon as we're shipping Jekyll 3.1.2 soon.

```console
$ gem install jekyll-docs -v 3.0.3
$ gem install jekyll -v 3.0.3
$ jekyll _3.0.3_ docs
```

:tada:

**Closed by parkr** 2016-02-20 01:25 UTC
Labels: bug

**Comment by didito** [comment] 2016-03-14 21:39
hello, i had trouble with the same things. tried installing and uninstalling several times. 
always got blocked by:

```bash
$ jekyll docs
Configuration file: /Users/blah/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-docs-3.1.2/site/_config.yml
            Source: /Users/blah/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-docs-3.1.2/site
       Destination: /var/folders/_7/g8qsmwrn6996ny2nvx013cmr0000gq/T/d20160314-38926-8zxbhe
 Incremental build: disabled. Enable with --incremental
      Generating...
  Dependency Error: Yikes! It looks like you don't have pygments or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- pygments' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
  Liquid Exception: pygments in /Users/blah/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-docs-3.1.2/site/_docs/assets.md
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    pygments
```
all i wanted is to have the jekyll docs locally on my mac (osx 10.10). but i am not a ruby / gems person, so I could just follow the commands on the jekyll homepage. i managed to install all the required gems for jekyll docs - not sure why this whole package system can't autoinstall all the dependencies like apt-get, i thought that was the point of it, but well ... - except **pygments**.

`gem install pygments` did not work, so i thought i might need to install it via pip (`pip install Pygments`) but that did not work either. ultimately i discovered i need the gem **_"pygments.rb"_**, so `gem install pygments.rb` did the trick.

maybe the error message or documentation / manual should mention that dependency more clearly, at least for newbies like me ...

**Comment by arikon** [comment] 2017-03-22 06:27
Same issue

```
➜  wat-2017-03-02 git:(master) jekyll docs
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.
➜  wat-2017-03-02 git:(master) gem list --local

*** LOCAL GEMS ***

addressable (2.5.0)
bigdecimal (1.2.0)
CFPropertyList (2.2.8)
colorator (1.1.0)
ffi (1.9.17)
forwardable-extended (2.6.0)
io-console (0.4.2)
jekyll (3.4.3, 3.4.0, 3.3.1)
jekyll-docs (3.3.1)
jekyll-sass-converter (1.5.0)
jekyll-watch (1.5.0)
json (1.7.7)
kramdown (1.13.2)
libxml-ruby (2.6.0)
liquid (3.0.6)
listen (3.0.8)
mercenary (0.3.6)
minitest (4.3.2)
nokogiri (1.5.6)
pathutil (0.14.0)
psych (2.0.0)
public_suffix (2.0.5)
rake (0.9.6)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rdoc (4.0.0)
rouge (1.11.1)
safe_yaml (1.0.4)
sass (3.4.23)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
```

**Comment by parkr** [comment] 2017-03-22 15:10
```
jekyll (3.4.3, 3.4.0, 3.3.1)
jekyll-docs (3.3.1)
```

The jekyll-docs version must match the jekyll version. We don't make that clear in our error message. I just released the docs for the 3.4.x. series, so you can now `gem install jekyll-docs -v 3.4.3` or `-v 3.4.0` and it will work with that version of jekyll.

**Comment by jemagee** [comment] 2017-03-22 17:58
@parkr 

Two suggestions for solutions, neither of which I know how to do

1.  When someone upgrades the jekyll gem it should check that the jekyll-docs is the right/matching version
2.  The error should state that the docs gem must match the jekyll version

**Comment by parkr** [comment] 2017-03-22 18:10
Hey y'all, what do you think of https://github.com/jekyll/jekyll/pull/5974 ?

**Comment by denjn5** [comment] 2017-07-12 12:25
Let me know if you'd prefer I start a new bug report, but I'm having a similar problem mentioned above (jekyll build & jekyll serve work fine):  

```
$ jekyll -v
jekyll 3.5.0

$ gem install jekyll-docs
Successfully installed jekyll-docs-3.4.3
Parsing documentation for jekyll-docs-3.4.3
Done installing documentation for jekyll-docs after 0 seconds
1 gem installed

$ jekyll docs
You must install the 'jekyll-docs' gem version = 3.5.0 to use the 'jekyll docs' command. 

$ gem install jekyll-docs -v 3.5.0
ERROR:  Could not find a valid gem 'jekyll-docs' (= 3.5.0) in any repository
ERROR:  Possible alternatives: jekyll-docs
```

I am not ruby-savvy. So I might be missing something obvious.  But feeling stuck...

Thanks for any guidance,
David

**Comment by parkr** [comment] 2017-07-17 20:17
We couldn't build the v3.5.0 docs due to a bug. v3.5.1 is out!

**Comment by karanshah89** [comment] 2017-07-27 13:23
I'm getting the same issue with v3.5.1

```
$ gem install jekyll-docs
Fetching: jekyll-docs-3.5.1.gem (100%)
Successfully installed jekyll-docs-3.5.1
Parsing documentation for jekyll-docs-3.5.1
Installing ri documentation for jekyll-docs-3.5.1
Done installing documentation for jekyll-docs after 0 seconds
1 gem installed

$ jekyll docs
You must install the 'jekyll-docs' gem version = 3.5.1 to use the 'jekyll docs' command. 
```

**Comment by weibeld** [comment] 2017-09-23 12:09
I had the same issue when I tried to install and run the `jekyll-docs` gem from within the root directory of my Jekyll project. However, just `cd`ing out of this directory makes the installation and running `jekyll docs` work without any problems.

**Comment by GuiltyPixel** [comment] 2018-02-16 03:06
I can confirm the behaviour from comment 331629828, changing directory from the project root causes 'jekyll docs' to succeed.

**Comment by orizagajones** [comment] 2018-05-14 17:36
Trying to install jekyll docs with not much luck. Using `sudo` worked for installing bundler & jekyll, but even when I specify that I want to install the matching version of Jekyll docs (3.8.1) it gives me grief. 

`cd`ing didn't help, unfortunately. here's what I got below:

```
Fetching: jekyll-docs-3.8.1.gem (100%)
Successfully installed jekyll-docs-3.8.1
Parsing documentation for jekyll-docs-3.8.1
Installing ri documentation for jekyll-docs-3.8.1
Done installing documentation for jekyll-docs after 0 seconds
1 gem installed
rhiannon@Rhiannon-Orizaga:~$ jekyll docs
You must install the 'jekyll-docs' gem version = 3.8.1 to use the 'jekyll docs' command. 
```

**Comment by PKHG** [comment] 2019-05-16 09:08
Still not solved:

C:\PKHG\jekyllTest16mei\test>jekyll docs
You must install the 'jekyll-docs' gem version = 3.8.5 to use the 'jekyll docs' command.

jekyll (3.8.5)
jekyll-docs (3.8.5)
jekyll-feed (0.12.1)
jekyll-sass-converter (1.5.2)
jekyll-seo-tag (2.6.0)
jekyll-watch (2.2.1)

Windows 10
